### PR TITLE
Update install.xml

### PR DESCRIPTION
**Pull request by obikenoby**
disallow add_cart in case of zero price

### CODE REVIEW

**Comment by trydalcoholic** [comment]
Hello!
I do not quite understand what exactly you want to do.
Now there is a condition that if the product is over and it is forbidden to order such goods in the settings, the add to cart button will be disabled. In other cases, the button will always work.

**Comment by obikenoby** [comment]
In case of setting the price to zero for example by the mistake and the condition that if the product is over is enabled, you can buy the zero priced product. And I'd like to create prevention of this situation.

**Comment by trydalcoholic** [comment]
But there is no longer any correction required. If the product is over and it is forbidden to order such goods in the settings, it can not be ordered, regardless of its price.

**Comment by obikenoby** [comment]
Yes, you are right, but it is only one point of view. The second point of view is that you allow to show products which is out of the stock and by mistake set the price to zero, or you have another reason to set the price to 0. Than everybody can buy this product and it isn't wanted behavior. That's why is the reason of my suggestion. 
If you think it's useless, please, ignore this suggestion :) I will use it by my modification in opencart. I thought it's useful for other people to not "show" add cart in this case.

**Comment by ZeppyShiddiq** [comment]
In many stores especially in manufacturing industry or custom design shops, the goods will be made after received an order (Make-to-order - MTO) instead of keeping in stock or made prior to an order (Make-to-Stock - MTS). In this case Customers need to possible to ordering the goods with the availability status of "Pre-Order" or "0" stock.

I've made small ext.to enable add-to-cart for "Pre-Order" or "0" stock. : https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=35272

**Comment by obikenoby** [comment]
It makes sense.

**Pull request closed without merging**
